// <auto-generated/>

using Microsoft.AspNetCore.Hosting;

[assembly: HostingStartup(typeof(FitnessCare.Web.Areas.Identity.IdentityHostingStartup))]
namespace FitnessCare.Web.Areas.Identity
{
    public class IdentityHostingStartup : IHostingStartup
    {
        public void Configure(IWebHostBuilder builder)
        {
            builder.ConfigureServices((context, services) => {
            });
        }
    }
}