// <auto-generated/>

using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FitnessCare.Data;
using FitnessCare.Data.Models;
using Microsoft.AspNetCore.Authorization;
using FitnessCare.Common;

namespace FitnessCare.Web.Areas.Administration.Controllers
{
    [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
    [Area("Administration")]
    public class ExercisesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ExercisesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Administration/Exercises
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Exercises.Include(e => e.MuscleGroup).Include(e => e.Workout);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Administration/Exercises/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var exercise = await _context.Exercises
                .Include(e => e.MuscleGroup)
                .Include(e => e.Workout)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (exercise == null)
            {
                return NotFound();
            }

            return View(exercise);
        }

        // GET: Administration/Exercises/Create
        public IActionResult Create()
        {
            ViewData["MuscleGroupId"] = new SelectList(_context.MuscleGroups, "Id", "Name");
            ViewData["WorkoutId"] = new SelectList(_context.Workouts, "Id", "UserId");
            return View();
        }

        // POST: Administration/Exercises/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,MuscleGroupId,WorkoutId,IsDeleted,DeletedOn,Id,CreatedOn,ModifiedOn")] Exercise exercise)
        {
            if (ModelState.IsValid)
            {
                _context.Add(exercise);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MuscleGroupId"] = new SelectList(_context.MuscleGroups, "Id", "Name", exercise.MuscleGroupId);
            ViewData["WorkoutId"] = new SelectList(_context.Workouts, "Id", "UserId", exercise.WorkoutId);
            return View(exercise);
        }

        // GET: Administration/Exercises/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var exercise = await _context.Exercises.FindAsync(id);
            if (exercise == null)
            {
                return NotFound();
            }
            ViewData["MuscleGroupId"] = new SelectList(_context.MuscleGroups, "Id", "Name", exercise.MuscleGroupId);
            ViewData["WorkoutId"] = new SelectList(_context.Workouts, "Id", "UserId", exercise.WorkoutId);
            return View(exercise);
        }

        // POST: Administration/Exercises/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Name,MuscleGroupId,WorkoutId,IsDeleted,DeletedOn,Id,CreatedOn,ModifiedOn")] Exercise exercise)
        {
            if (id != exercise.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(exercise);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ExerciseExists(exercise.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["MuscleGroupId"] = new SelectList(_context.MuscleGroups, "Id", "Name", exercise.MuscleGroupId);
            ViewData["WorkoutId"] = new SelectList(_context.Workouts, "Id", "UserId", exercise.WorkoutId);
            return View(exercise);
        }

        // GET: Administration/Exercises/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var exercise = await _context.Exercises
                .Include(e => e.MuscleGroup)
                .Include(e => e.Workout)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (exercise == null)
            {
                return NotFound();
            }

            return View(exercise);
        }

        // POST: Administration/Exercises/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var exercise = await _context.Exercises.FindAsync(id);
            _context.Exercises.Remove(exercise);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ExerciseExists(int id)
        {
            return _context.Exercises.Any(e => e.Id == id);
        }
    }
}
