// <auto-generated/>

using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using FitnessCare.Data;
using FitnessCare.Data.Models;
using Microsoft.AspNetCore.Authorization;
using FitnessCare.Common;

namespace FitnessCare.Web.Areas.Administration.Controllers
{
    [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
    [Area("Administration")]
    public class WorkoutTypesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public WorkoutTypesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Administration/WorkoutTypes
        public async Task<IActionResult> Index()
        {
            return View(await _context.WorkoutTypes.ToListAsync());
        }

        // GET: Administration/WorkoutTypes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var workoutType = await _context.WorkoutTypes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (workoutType == null)
            {
                return NotFound();
            }

            return View(workoutType);
        }

        // GET: Administration/WorkoutTypes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Administration/WorkoutTypes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,IsDeleted,DeletedOn,Id,CreatedOn,ModifiedOn")] WorkoutType workoutType)
        {
            if (ModelState.IsValid)
            {
                _context.Add(workoutType);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(workoutType);
        }

        // GET: Administration/WorkoutTypes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var workoutType = await _context.WorkoutTypes.FindAsync(id);
            if (workoutType == null)
            {
                return NotFound();
            }
            return View(workoutType);
        }

        // POST: Administration/WorkoutTypes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Name,IsDeleted,DeletedOn,Id,CreatedOn,ModifiedOn")] WorkoutType workoutType)
        {
            if (id != workoutType.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(workoutType);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!WorkoutTypeExists(workoutType.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(workoutType);
        }

        // GET: Administration/WorkoutTypes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var workoutType = await _context.WorkoutTypes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (workoutType == null)
            {
                return NotFound();
            }

            return View(workoutType);
        }

        // POST: Administration/WorkoutTypes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var workoutType = await _context.WorkoutTypes.FindAsync(id);
            _context.WorkoutTypes.Remove(workoutType);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool WorkoutTypeExists(int id)
        {
            return _context.WorkoutTypes.Any(e => e.Id == id);
        }
    }
}
